# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-09 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20171209_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
