# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-12 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_thing_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired', models.CharField(choices=[('purchased', 'purchased'), ('gifted', 'Gifted'), ('inherited', 'Inherited'), ('other', 'Other')], max_length=255)),
                ('years', models.CharField(choices=[('Less than one', 'Less than one year'), ('One year', 'One year'), ('More than one', 'More than one year')], max_length=255)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquired', to='inventory.Thing')),
            ],
        ),
    ]
