# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-14 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_thinghistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThingTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('gift', 'gift'), ('seasonal', 'seasonal'), ('inherited', 'inherited'), ('clothing', 'clothing'), ('shoes', 'shoes'), ('furniture', 'furniture')], max_length=255)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquired', to='inventory.Thing')),
            ],
        ),
        migrations.RemoveField(
            model_name='thinghistory',
            name='thing',
        ),
        migrations.DeleteModel(
            name='ThingHistory',
        ),
    ]
