# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-14 05:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20171214_0454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thingtag',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='thing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 12, 14, 5, 57, 7, 514025, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thing',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 12, 14, 5, 57, 20, 341435, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thingtag',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='inventory.Thing'),
        ),
    ]
