# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-14 07:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_blogarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 12, 14, 7, 55, 41, 483686, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 12, 14, 7, 55, 46, 890638, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
