# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-24 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20171214_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=inventory.models.get_image_path)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='inventory.Thing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
