# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-15 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer_type', models.CharField(choices=[('open', 'open'), ('radio', 'radio'), ('checkbox', 'checkbox'), ('number', 'number'), ('truefalse', 'truefalse')], max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
